# This script is generated by a GUI libero flow. 
# !! WARNING This script has been modified !!
set max_timing_multi_corner [report \
    -type     timing \
    -analysis max \
    -multi_corner yes \
    -max_paths 100000 \
    -max_expanded_paths 100000 \
    -format   text \
    {wrap_timing_10000_paths_expanded.rpt}]
set max_timing_violations_multi_corner [report \
    -type     timing_violations \
    -analysis max \
    -multi_corner yes \
    -format   text \
    -use_slack_threshold no \
    -max_paths 100000 \
    {wrap_timing_10000_paths.rpt}]
set has_violations {wrap_has_violations}
set fp [open $has_violations w]
puts $fp "_max_timing_violations_multi_corner $max_timing_violations_multi_corner"
puts $fp "_max_timing_multi_corner $max_timing_multi_corner"
close $fp
