# Generate Cache_Decls_RV32.bsv    for RV32.Sv32

.PHONY: default
default:
	./Gen_BSV_Cache_Decls.py  --yaml_file  RV32_Sv32_args.yaml

.PHONY: RV64_SV39
RV64_SV39:
	./Gen_BSV_Cache_Decls.py  --yaml_file  RV64_Sv39_args.yaml
