###  -*-Makefile-*-

# Copyright (c) 2018 Bluespec, Inc. All Rights Reserved

# ================================================================

include ../Resources/Include_RV64ACIMSU.mk

include ../Resources/Include_Bluesim.mk

# ================================================================
